# Generated by Django 6.0.4 on 2026-04-23 05:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True / False"),
                            ("essay", "Essay"),
                            ("code", "Code"),
                        ],
                        default="multiple_choice",
                        max_length=20,
                        verbose_name="question type",
                    ),
                ),
                ("text", models.TextField(verbose_name="question text")),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Ditampilkan setelah student menjawab",
                        verbose_name="explanation",
                    ),
                ),
                (
                    "points",
                    models.PositiveSmallIntegerField(default=1, verbose_name="points"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="quiz/questions/"
                    ),
                ),
                (
                    "code_language",
                    models.CharField(
                        blank=True,
                        help_text="Contoh: python, javascript, sql",
                        max_length=30,
                        verbose_name="code language",
                    ),
                ),
                (
                    "code_template",
                    models.TextField(
                        blank=True,
                        help_text="Kode awal yang ditampilkan di editor",
                        verbose_name="code template",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
                "db_table": "quiz_questions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="answer text")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="is correct"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True,
                        help_text="Feedback khusus jika jawaban ini dipilih",
                        verbose_name="per-answer feedback",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quizzes.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "answer",
                "verbose_name_plural": "answers",
                "db_table": "quiz_answers",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "pass_score",
                    models.PositiveSmallIntegerField(
                        default=70,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="pass score (%)",
                    ),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 = tidak ada batas waktu",
                        verbose_name="time limit (seconds)",
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="0 = tidak terbatas",
                        verbose_name="max attempts",
                    ),
                ),
                (
                    "randomize_questions",
                    models.BooleanField(
                        default=False, verbose_name="randomize questions"
                    ),
                ),
                (
                    "randomize_answers",
                    models.BooleanField(
                        default=False, verbose_name="randomize answers"
                    ),
                ),
                (
                    "show_feedback",
                    models.BooleanField(
                        default=True, verbose_name="show feedback after submit"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "quiz",
                "verbose_name_plural": "quizzes",
                "db_table": "quizzes",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quizzes.quiz",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["quiz", "order"], name="quiz_questi_quiz_id_76bc24_idx"
            ),
        ),
    ]
